FROM python:3.10.4-alpine3.15

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY djangoProject .

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
